- job-template:
    name: fuel-ccp-{component}-{version}-deployment
    description: |
      Deploy CCP and run basic OpenStack tests (uses snapshot for K8s cluster)
    node: standard
    builders:
      - inject:
          properties-content: |
            COMPONENT={component}
            VERSION={version}
      - shell:
          !include-raw-escape 'builders/fuel-ccp-simple-deployment.sh'
    publishers:
      - post-tasks:
          - matches:
              - log-text: ''
            escalate-status: false
            run-if-job-successful: false
            script: |
              #!/bin/bash
              COMPONENT={component}
              VERSION={version}
              DOCKER_REGISTRY="registry.mcp.fuel-infra.org"
              IMAGES_NAMESPACE="ccp"
              REGISTRY_NAMESPACE="mcp"
              ENV_NAME="fuel-ccp-{component}-{version}-deployment"
              FUEL_DEVOPS_SNAPSHOT_NAME="fresh"
              FUEL_DEVOPS_INSTALLATION_DIR="/home/jenkins/venv-fuel-devops-3.0"
              IMAGES_TAG=$VERSION-unstable

              set -ex
              if [ "${COMPONENT}" == "smoke" ]; then
                  ADMIN_IP=$(ENV_NAME=${FUEL_DEVOPS_ENV_NAME} python fuel-ccp-installer/utils/jenkins/env.py get_slaves_ips | grep -o "[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+" | head -1)
                  SSH_COMMAND="sshpass -p vagrant ssh -o StrictHostKeyChecking=no vagrant@${ADMIN_IP}"
                  sshpass -p vagrant ssh -o StrictHostKeyChecking=no vagrant@"${ADMIN_IP}" mkdir -p /home/vagrant/.docker/
                  sshpass -p vagrant scp -o StrictHostKeyChecking=no /home/jenkins/.docker/config.json vagrant@"${ADMIN_IP}":~/.docker/
                  for f in ${IMG}; do
                      sshpass  -p vagrant ssh -o StrictHostKeyChecking=no vagrant@"${ADMIN_IP}" \
                      "docker tag 127.0.0.1:31500/${IMAGES_NAMESPACE}/$f:latest ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${f}:${IMAGES_TAG} && docker push ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${f}:${IMAGES_TAG}"
                      if [ "${IMAGES_TAG}" == "ocata" ]; then
                          sshpass  -p vagrant ssh -o StrictHostKeyChecking=no vagrant@"${ADMIN_IP}" \                                                                                           "docker tag 127.0.0.1:31500/${IMAGES_NAMESPACE}/${f}:latest ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${f}:latest-unstable \
                          && docker push ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${f}:latest-unstable"
                      fi
                   done
              fi
              source "$FUEL_DEVOPS_INSTALLATION_DIR"/bin/activate
              echo "Running on $NODE_NAME: $ENV_NAME"
              virsh list --all
              dos.py revert "$ENV_NAME" "$FUEL_DEVOPS_SNAPSHOT_NAME"
              dos.py destroy "$ENV_NAME"
              deactivate
    concurrent: true
    properties:
      - heavy-job:
          weight: 2
      - throttle:
          option: project
          max-per-node: 1
      - least-load:
          disabled: False
    scm:
      - openstack:
          scm-basedir: 'fuel-ccp'
          scm-branch: 'master'
          scm-repo: 'fuel-ccp'
      - openstack:
          scm-basedir: 'fuel-ccp-installer'
          scm-branch: 'master'
          scm-repo: 'fuel-ccp-installer'
    wrappers:
      - ng-cleanup

- project:
    name: Deploy CCP and run basic OpenStack tests (uses snapshot for K8s cluster)
    version:
      - master
      - newton
    component:
      - smoke
      - full
      - debian-base
      - etcd
      - mariadb
      - memcached
      - rabbitmq
      - stacklight
      - cinder
      - glance
      - heat
      - horizon
      - ironic
      - keystone
      - murano
      - neutron
      - nova
      - openstack-base
      - sahara
    jobs:
      - 'fuel-ccp-{component}-{version}-deployment'
