pipelines:
  - name: check
    description: Newly uploaded patchsets enter this pipeline to receive an initial +/-1 Verified vote from Jenkins.
    success-message: Build succeeded (check pipeline).
    failure-message: Build failed (check pipeline).  For information on how to proceed, see http://docs.openstack.org/infra/manual/developers.html#automated-testing
    manager: IndependentPipelineManager
    source: gerrit
    precedence: normal
    require:
      open: True
      current-patchset: True
    trigger:
      gerrit:
        - event: patchset-created
        - event: change-restored
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(recheck|reverify|ccp-recheck)
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1

  - name: post
    description: This pipeline runs jobs that operate after each change is merged.
    manager: IndependentPipelineManager
    source: gerrit
    precedence: low
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^(?!refs/).*$


project-templates:
  - name: verify-tox
    check:
      - 'verify-tox-pep8'
      - 'verify-tox-py27'

projects:
  - name: openstack-dev/ci-sandbox
    check:
      - verify-tox-py27
      - verify-tox-pep8

  - name: openstack/fuel-ccp-nextgen-specs
    check:
      - verify-tox-pep8

  - name: openstack/fuel-ccp
    check:
      - fuel-ccp-gate-job

  - name: openstack/fuel-ccp-debian-base
    check:
      - test-build-base

  - name: openstack/fuel-ccp-ext-config
    check:
      - fuel-ccp-ext-config-gate-job

  - name: openstack/fuel-ccp-etcd
    check:
      - test-build-etcd

  - name: openstack/fuel-ccp-glance
    check:
      - test-build-glance

  - name: openstack/fuel-ccp-horizon
    check:
      - test-build-horizon

  - name: openstack/fuel-ccp-keystone
    check:
      - test-build-keystone

  - name: openstack/fuel-ccp-mariadb
    check:
      - test-build-mariadb

  - name: openstack/fuel-ccp-memcached
    check:
      - test-build-memcached

  - name: openstack/fuel-ccp-neutron
    check:
      - test-build-neutron

  - name: openstack/fuel-ccp-nova
    check:
      - test-build-nova

  - name: openstack/fuel-ccp-openstack-base
    check:
      - test-build-openstackbase

  - name: openstack/fuel-ccp-rabbitmq
    check:
      - test-build-rabbitmq

  - name: openstack/fuel-ccp-installer
    check:
      - fuel-ccp-installer

  - name: openstack/fuel-ccp-tests
    check:
      - fuel-ccp-mcp-qa

  - name: openstack/fuel-ccp-ci-config
    check:
      - verify-jjb-project-config
    post:
      - update-jenkins-jobs

