pipelines:
  - name: check
    description: Verify new patchset
    success-message: Build succeeded
    failure-message: Build failed
    manager: IndependentPipelineManager
    source: gerrit
    precedence: normal
    require:
      open: True
      current-patchset: True
    trigger:
      gerrit:
        - event: patchset-created
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(recheck|reverify)
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verfied: -1

  - name: gate
    description: Test after verifed and workflow
    success-message: Build succeded
    failure-message: Build failed
    manager: DependentPipelineManager
    source: gerrit
    precedence: high
    require:
      open: True
      current-patchset: True
      approval:
        - verified: [1,2]
          username: nextgen-ci
        - workflow: 1
    trigger:
      gerrit:
        - event: comment-added
          approval:
            - workflow: 1
        - event: comment-added
          approval:
            - verified: 1
              username: nextgen-ci
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
        verified: 2
        submit: true
    failure:
      gerrit:
        verfied: -2

  - name: post
    description: Job run after merge
    manager: IndependentPipelineManager
    source: gerrit
    precedence: low
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^(?!refs/).*$

project-templates:
  - name: verify-tox
    check:
      - 'verify-tox-pep8'
      - 'verify-tox-py27'

projects:
  - name: nextgen/nextgen-specs
    check:
      - verify-tox-py27-nextgen-specs
      - verify-tox-pep8-nextgen-specs
    post:
      - nextgen-docs-build-jobs

  - name: openstack/kolla
    template:
      - name: verify-tox

  - name: tools/ng-ci-scripts
    check:
      - ng-scripts-check-triggered-job
    gate:
      - ng-scripts-gate-triggered-job
    post:
      - ng-scripts-post-triggered-job
  - name: nextgen/microservices
    template:
      - name: verify-tox
    gate:
      - nextgen-microservices-gate-job

  - name: nextgen/ms-aodh
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-aodh-gate-job

  - name: nextgen/ms-ceilometer
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-ceilometer-gate-job

  - name: nextgen/ms-ceph
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-ceph-gate-job

  - name: nextgen/ms-cinder
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-cinder-gate-job

  - name: nextgen/ms-debian-base
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-debian-base-gate-job

  - name: nextgen/ms-designate
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-designate-gate-job

  - name: nextgen/ms-elasticsearch
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-elasticsearch-gate-job

  - name: nextgen/ms-ext-config
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-ext-config-gate-job

  - name: nextgen/ms-glance
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-glance-gate-job

  - name: nextgen/ms-heat
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-heat-gate-job

  - name: nextgen/ms-heka
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-heka-gate-job

  - name: nextgen/ms-horizon
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-horizon-gate-job

  - name: nextgen/ms-ironic
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-ironic-gate-job

  - name: nextgen/ms-kibana
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-kibana-gate-job

  - name: nextgen/ms-magnum
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-magnum-gate-job

  - name: nextgen/ms-manila
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-manila-gate-job

  - name: nextgen/ms-mariadb
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-mariadb-gate-job

  - name: nextgen/ms-memcached
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-memcached-gate-job

  - name: nextgen/ms-mistral
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-mistral-gate-job

  - name: nextgen/ms-mongodb
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-mongodb-gate-job

  - name: nextgen/ms-murano
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-murano-gate-job

  - name: nextgen/ms-neutron
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-neutron-gate-job

  - name: nextgen/ms-nova
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-nova-gate-job

  - name: nextgen/ms-openstack-base
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-openstack-base-gate-job

  - name: nextgen/ms-openvswitch
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-openvswitch-gate-job

  - name: nextgen/ms-rabbitmq
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-rabbitmq-gate-job

  - name: nextgen/ms-sahara
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-sahara-gate-job

  - name: nextgen/ms-swift
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-swift-gate-job

  - name: nextgen/ms-tempest
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-tempest-gate-job

  - name: nextgen/ms-toolbox
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-toolbox-gate-job

  - name: nextgen/ms-trove
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-trove-gate-job

  - name: nextgen/ms-zaqar
    template:
      - name: verify-tox
    gate:
      - nextgen-ms-zaqar-gate-job
