pipelines:
  - name: check
    description: Verify new patchset
    success-message: Build succeeded
    failure-message: Build failed
    manager: IndependentPipelineManager
    source: gerrit
    precedence: normal
    require:
      open: True
      current-patchset: True
    trigger:
      gerrit:
        - event: patchset-created
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(recheck|reverify)
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verfied: -1

project-templates:
  - name: verify-tox
    check:
      - 'verify-tox-pep8'
      - 'verify-tox-py27'

projects:
  - name: openstack-dev/ci-sandbox
    check:
      - verify-tox-py27
      - verify-tox-pep8


