#!/bin/bash
set -x

#add user
useradd -s /bin/bash -m jenkins
usermod jenkins -a -G sudo,docker,libvirtd

#add pubkey
mkdir /home/jenkins/.ssh
cat > /home/jenkins/.ssh/authorized_keys <<EOF
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKUgMk+HhqWFV3CwFdqsttUAqen+q5ahjb2DcFWcd8VaXK2dGHVugIa1bcHqWXYCXcqDDNWsB35XBJ7eEz26Hz5y40LKPu5wsTiWJpBAXuBWjxenz+9TK9Q3vZp6IqkiOx+3MJzXBw0iY6qn4lLfpfPjHqDDMQsFmrBidDxSh8lcQFQZlm+XPaclOPMzFNJ5CgL12/UMQAj4g/FiA/7Xx5qjRQuwNdixrHSa9P9jAFCGEHnOJfNFCL5FGq4Nyy9WUXrRJtjh2n0tUh0r83m8CL+8WXaTEhjqNSXwcbJzrO+LVtRmpQOYJohvzCDuiB9djbhj3WlHuEJqLt4uq6SZ/p nodepool@nodepool01-scc.dev.mirantis.net
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvekMXZHXhlTQpiSqmrLrnwhf6YeIdCPgJA4C9I06F+XKU/VnwYfNAbToOSFyt5cRe8abfSDlkNrAD8ldiGneY4xXxG6sYVTuGYi5BEWvh4OL4BGgL4tNYEOx/udI6irYE+KvGKzZBH5dfvxsqZDoFdSHTbNI4eJRorCOVRhm6TLdm04FfSqrJlL4eMgFZLsICYhtIZe8ymq99XVoqgXf5y0e9pnkhAOI7NQSWI30K8nSK+NwvYK7f+rlG4DPvQNql/JKWOAUio2LCQFyPqeo06QgGvFnGX2Sntx3XD8bbxjZYFqn1IwHNClVOQCRNTku/QszLFBm15K5tTB4hyPnL jenkins@ci01-dev.ng.mirantis.net
EOF

#known_hosts
ssh-keyscan -p 29418 review.fuel-infra.org > /home/jenkins/.ssh/known_hosts

chmod 600 /home/jenkins/.ssh/authorized_keys
chmod 600 /home/jenkins/.ssh/known_hosts
chown -R jenkins:jenkins /home/jenkins/

#directory for nodepool metadata
mkdir /etc/nodepool
chown jenkins:jenkins /etc/nodepool

#workaround for old paramiko on nodepool host
cat >> /etc/ssh/sshd_config <<EOF
Ciphers aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,hmac-sha1
KexAlgorithms diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1
EOF

#libvirt dir for E2E tests
mkdir -p /var/lib/libvirt/images/kubernetes
chown jenkins:jenkins /var/lib/libvirt/images/kubernetes
