#!/bin/bash
set -x

#add user
useradd -s /bin/bash -m jenkins
usermod jenkins -a -G sudo

#add pubkey
mkdir /home/jenkins/.ssh
cat > /home/jenkins/.ssh/authorized_keys <<EOF
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKUgMk+HhqWFV3CwFdqsttUAqen+q5ahjb2DcFWcd8VaXK2dGHVugIa1bcHqWXYCXcqDDNWsB35XBJ7eEz26Hz5y40LKPu5wsTiWJpBAXuBWjxenz+9TK9Q3vZp6IqkiOx+3MJzXBw0iY6qn4lLfpfPjHqDDMQsFmrBidDxSh8lcQFQZlm+XPaclOPMzFNJ5CgL12/UMQAj4g/FiA/7Xx5qjRQuwNdixrHSa9P9jAFCGEHnOJfNFCL5FGq4Nyy9WUXrRJtjh2n0tUh0r83m8CL+8WXaTEhjqNSXwcbJzrO+LVtRmpQOYJohvzCDuiB9djbhj3WlHuEJqLt4uq6SZ/p nodepool@nodepool.ng.mirantis.net
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIFBD03r2yjZdaz84Znfb9e3Ng129wlgZopBgyEgqJk/7huzkkn5AiHqP27KLLXchonjuwlDp88YtaR6oZQlyPggVIIMxFzZ5RAPDhbBB19qUKSmAr1Bx8IdPg3jnLP1AxhaZe/+zBlVQgGk2Q4DMkia8K6ePPb4DflOiCDoXcajXZNuvDhHlgiFwBhJNopzhKvLJOH1yQ/36WbpU/NIMfMh6MCNBkCnxI+9SMncXneUHYgC71ajPEQtOhh7cdLhEICD+pF3n7I+DBumZ4azPz0vyTKq6EhlfBHrHe4krF/yL9BxVLhGU+Bh+1e8MfaaW/0K58Ii9zHAr4BDVV2t4l jenkins@jenkins.ng.mirantis.net
EOF

chmod 600 /home/jenkins/.ssh/authorized_keys
chown -R jenkins:jenkins /home/jenkins/

#directory for nodepool metadata
mkdir /etc/nodepool
chown jenkins:jenkins /etc/nodepool
